plugins {
	id 'war'
	id "org.gretty" version "3.1.1"
	id 'com.github.psxpaul.execfork' version '0.2.2'
	id 'jacoco'
}

jacoco {
	toolVersion = "0.8.11"
}

war {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// TODO: don't use gretty since gretty not supporting jetty 10.0.5 and gretty 4.0.0 only support jetty11+

java.sourceCompatibility = JavaVersion.VERSION_11
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
	options.warnings = false
}

repositories {
	mavenLocal() {
		content {
			excludeGroupByRegex "io\\.netty\\.*"
		}
	}

	maven {
		url = uri('https://mavensync.zkoss.org/maven2')
	}

	maven {
		url = uri('https://mavensync.zkoss.org/eval')
	}

	maven {
		url = uri('https://repo.maven.apache.org/maven2/')
	}

	maven {
		url = uri('https://maven.seasar.org/maven2')
	}

	maven {
		url = uri('https://maven.nuxeo.org/nexus/content/groups/public/')
	}

	maven {
		url = uri('https://maven.java.net/content/groups/public/')
	}

	maven {
		url = uri('https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/')
	}
}

// work for Servlet 3.0
configurations.all {
	exclude group: 'org.zkoss.zk', module: 'zkwebfragment'
}
// fix CDI(Weld) to scan from META-INF/beans.xml into build/classes/java/main/META-INF
task copyResources(type: Copy) {
	from "${projectDir}/src/main/resources/META-INF"
	into layout.buildDirectory.dir('classes/java/main/META-INF')
}

processResources.dependsOn copyResources

dependencies {
	implementation "org.zkoss.theme:breeze:10.0.1.1-Eval"
	implementation "org.zkoss.theme:silvertail:10.0.1.1-Eval"
	implementation "org.zkoss.theme:sapphire:10.0.1.1-Eval"
	implementation "org.zkoss.theme:atlantic:10.0.1.1-Eval"
	implementation 'commons-logging:commons-logging:1.1.1'
	implementation 'org.apache.commons:commons-fileupload2-jakarta-servlet6:2.0.0-M4'
	implementation 'commons-io:commons-io:2.17.0'
	implementation "org.zkoss.zk:zk:${version}"
	implementation "org.zkoss.zk:zkplus:${version}"
	implementation "org.zkoss.zk:zkbind:${version}"
	implementation "org.zkoss.zk:zul:${version}"
	implementation "org.zkoss.zk:zhtml:${version}"
	implementation "org.zkoss.common:zcommon:${version}"
	implementation "org.zkoss.common:zweb:${version}"
	implementation "org.zkoss.common:zweb-dsp:${version}"
	implementation "org.zkoss.common:zel:${version}"
	implementation "org.zkoss.zk:zkex:${version}"
	implementation "org.zkoss.zk:zkmax:${version}"
	implementation "org.zkoss.zk:zuti:${version}"
	if (project.ext['zktestWithoutA11y'] == 'false') {
		implementation "org.zkoss.zk:za11y:${version}"
	} else {
		testCompileOnly "org.zkoss.zk:za11y:${version}"
	}
	implementation 'org.zkoss.zkforge.el:zcommons-el:1.1.0'
	implementation 'org.apache.commons:commons-lang3:3.20.0'
	implementation 'commons-beanutils:commons-beanutils:1.9.4'
	implementation 'com.google.javascript:closure-compiler-unshaded:v20230802'
	implementation 'net.sf.jasperreports:jasperreports:6.20.5'
	implementation 'org.jfree:jfreechart:1.0.19'
	implementation 'com.jhlabs:filters:2.0.235-1'
	implementation 'org.zkoss.zkforge:ckez:4.21.0.0-jakarta'
	implementation 'org.zkoss.zkforge:timelinez:2.3.1_50'
	implementation 'org.zkoss.zkforge:timeplotz:1.1_50'
	implementation 'org.zkoss.zkforge:gmapsz:3.1.0'
	implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'

	// fix for DestroyTest.java that org.eclipse.jetty:apache-jsp:10.0.5 depends on slf4j-api 2.0.0-alpha1
	implementation 'org.slf4j:slf4j-jdk14:2.0.7'
	implementation 'jakarta.inject:jakarta.inject-api:2.0.1'
	implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0'
	implementation 'org.javassist:javassist:3.29.2-GA'
	implementation 'org.easymock:easymock:3.4'
	implementation 'de.odysseus.juel:juel-spi:2.2.7'
	implementation 'de.odysseus.juel:juel-impl:2.2.7'

	// ZK-5458
	implementation 'org.jboss.weld.servlet:weld-servlet-core:5.1.2.Final'

	runtimeOnly 'org.apache-extras.beanshell:bsh:2.0b6'
	runtimeOnly 'org.apache.groovy:groovy:5.0.0-alpha-1'
	runtimeOnly 'org.mozilla:rhino:1.8.1'
//	testImplementation 'org.jruby:jruby-core:1.7.27'
	runtimeOnly 'org.python:jython-slim:2.7.4'
	testImplementation 'org.zkoss.zats:zats-mimic:10.2.1-jakarta'
	testImplementation 'org.zkoss.zats:zats-mimic-ext:10.2.1-jakarta'
	testImplementation 'net.jcip:jcip-annotations:1.0'
	testImplementation 'com.deque.html.axe-core:selenium:4.7.0'
	testImplementation 'org.springframework.session:spring-session-core:2.1.6.RELEASE'
	testImplementation "org.junit.jupiter:junit-jupiter-api:$junitVersion"
	testImplementation "org.mockito:mockito-inline:4.7.0"
	testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
	testImplementation 'org.eclipse.jetty.ee10:jetty-ee10-apache-jsp:12.0.10'
	testImplementation 'org.junit.platform:junit-platform-launcher:1.9.0'
	testImplementation 'xml-apis:xml-apis:1.4.01'
	testImplementation 'org.zkoss.test:zk-webdriver:1.4.39.0.2'

	// For B96_ZK_4194Test and F102_ZK_5461Test to use a specific Chrome driver version (this will change to match latest chrome)
	testImplementation 'org.seleniumhq.selenium:selenium-devtools-v143:4.39.0'
	testImplementation "org.seleniumhq.selenium:selenium-java:4.39.0"
	testImplementation 'com.google.javascript:closure-compiler-unshaded:v20230802'

	providedCompile 'jakarta.el:jakarta.el-api:4.0.0'
	providedCompile 'jakarta.servlet:jakarta.servlet-api:5.0.0'
	providedCompile 'jakarta.websocket:jakarta.websocket-api:2.0.0'
	// workaround for running Mockito under Java 11
	providedCompile "net.bytebuddy:byte-buddy:1.8.22"
	providedCompile "net.bytebuddy:byte-buddy-agent:1.8.22"
}

sourceSets {
	main {
		resources {
			// some test will try to get content from resources
			srcDirs += "src/main/webapp"
		}
		java {
			// Uses Filedownload.DownloadItem / saveMultiple() added after 10.2.1-jakarta
			exclude 'org/zkoss/zktest/test2/F103_ZK_5908_MultipleFileDownloadComposer.java'
		}
	}
	test {
		java {
			// These tests use Jetty 10 APIs (JarResource, ResourceCollection, HandlerList, Resource.newResource)
			// which were removed in Jetty 12 (jakarta). Exclude them from compilation.
			exclude 'org/zkoss/zktest/zats/test2/B80_ZK_3123Test.java'
			exclude 'org/zkoss/zktest/zats/test2/F102_ZK_5640Test.java'
			exclude 'org/zkoss/zktest/zats/test2/F102_ZK_5640_1Test.java'
			exclude 'org/zkoss/zktest/zats/test2/F102_ZK_5640_2Test.java'
			exclude 'org/zkoss/zktest/zats/test2/F102_ZK_5640_3Test.java'
			exclude 'org/zkoss/zktest/zats/test2/B86_ZK_4288Test.java'
			exclude 'org/zkoss/zktest/zats/test2/B90_ZK_4381Test.java'

		}
	}
}

task testGroupForkJVMTestOnly(type: Test) {

	forkEvery = 1 // a new test process is started for every test class
	maxParallelForks = Runtime.runtime.availableProcessors().intdiv(4) ?: 1
	if (project.hasProperty('maxParallelForks'))
		maxParallelForks = project.maxParallelForks as int


	exclude 'org/zkoss/zktest/zats/wcag/**'

	if (project.ext['zktestWithoutA11y'] != 'false') {
		reports.junitXml.destination = file("$buildDir/test-results/no-A11Y/testGroupForkJVMTestOnly")
		useJUnitPlatform {
			includeTags 'ForkJVMTestOnly'
			excludeTags 'WcagTestOnly'
		}
	} else {
		useJUnitPlatform {
			includeTags 'ForkJVMTestOnly'
		}
	}
	systemProperty "zkWebdriverContextPath", "/zktest"
	systemProperty "zkWebdriverTestURLPackage", "org.zkoss.zktest.zats"

	// a way to pass -Dtags=...
	options {
		systemProperties(System.getProperties())
	}

	// for Jenkins' info
	testLogging {
		events("standardOut", "started", "passed", "skipped", "failed")
	}
}

task npmInstallLighthouse(type: Exec) {
	outputs.dir("${project.buildDir}/lighthouse/")
	commandLine 'npm', 'install', '-g', 'lighthouse@12.2.0'
}
task testWCAGOnly(type: Test) {
	dependsOn npmInstallLighthouse
	forkEvery = 1 // a new test process is started for every test class
	maxParallelForks = 1 // default 1 process, because it will hang in Jenkins
	if (project.hasProperty('maxParallelForks'))
		maxParallelForks = project.maxParallelForks as int

	include 'org/zkoss/zktest/zats/wcag/**'

	systemProperty "zkWebdriverContextPath", "/zktest"
	systemProperty "zkWebdriverTestURLPackage", "org.zkoss.zktest.zats"

	// a way to pass -Dtags=...
	options {
		systemProperties(System.getProperties())
	}

	useJUnitPlatform();

	// for Jenkins' info
	testLogging {
		events("standardOut", "started", "passed", "skipped", "failed")
	}
}
test {
	forkEvery = 1
	maxParallelForks = Runtime.runtime.availableProcessors().intdiv(4) ?: 1
	if (project.hasProperty('maxParallelForks'))
		maxParallelForks = project.maxParallelForks as int

	exclude 'org/zkoss/zktest/zats/wcag/**'

	if (project.ext['zktestWithoutA11y'] != 'false') {
		reports.junitXml.destination = file("$buildDir/test-results/no-A11Y/test")
		useJUnitPlatform {
			excludeTags 'WcagTestOnly', 'ForkJVMTestOnly'
		}
	} else {
		useJUnitPlatform {
			excludeTags 'ForkJVMTestOnly'
		}
	}
	systemProperty "zkWebdriverContextPath", "/zktest"
	systemProperty "zkWebdriverTestURLPackage", "org.zkoss.zktest.zats"

	// a way to pass -Dtags=...
	options {
		systemProperties(System.getProperties())
	}

	// for Jenkins' info
	testLogging {
		events("standardOut", "started", "passed", "skipped", "failed")
	}

	maxHeapSize = "1024m"
	jvmArgs '-XX:MaxMetaspaceSize=1024m'

	// jacoco coverage report
	if (project.ext['zktestWithJacoco'] == 'true')
		finalizedBy jacocoTestReport
}

task clearNoA11Y(type: Delete) {
	delete "$buildDir/test-results/no-A11Y/"
}

task renameNoA11yTestResult (type: Copy) {
//	mustRunAfter test
//	mustRunAfter 'testGroupForkJVMTestOnly'
//	setOnlyIf { project.ext['zktestWithoutA11y'] != 'false' }
	destinationDir = file("$buildDir/test-results/no-A11Y0")
	from ("$buildDir/test-results/no-A11Y")
	includeEmptyDirs false
	include '**/*Test.xml'
	filter {
		String line -> line.replaceAll("testsuite name=\"(.[^\"]*)\"",
				"testsuite name=\"\$1(NO_A11Y)\"")
	}
	rename '(.*).xml', '$1NO_A11Y.xml'

	finalizedBy clearNoA11Y
}

description = 'ZK Test'


gretty {
	if (project.hasProperty('httpPort')) {
		httpPort = Integer.parseInt(project.httpPort)
	}
	systemProperty 'java.util.logging.config.file', './src/main/webapp/WEB-INF/logging.properties'
	reloadOnClassChange    = false // disable reloading when classes changes
}

// Start browsersync in the background.
// Failed attempt:
//   Use `ant.exec` instead of `exec`: https://stackoverflow.com/a/43501772
//   However, the synatx for `arg` in the link above is wrong: https://discuss.gradle.org/t/running-ant-exec-with-env-attribute/11001
//   Unfortunately, the spawned process will not be killed.
//   ```
//   ant.exec(executable: 'npm', spawn: true) {
// 	   arg(value: 'run')
// 	   arg(value: 'dev')
// 	   arg(value: '--')
// 	   arg(value: '--port')
// 	   arg(value: gretty.httpPort)
// 	   arg(value: '--startPath')
// 	   arg(value: '/zephyr-test')
//   }
// Beware that specifying `waitForPort` below could cause the spawned process to not be killed.
// In that case, check for `ps aux | grep gulp` and `localhost:300{n}` where n is odd.
task browsersync(type: com.github.psxpaul.task.ExecFork) {
    executable = 'npm'
    args = ['run', 'dev', '--', '--port', "${gretty.httpPort}", '--startPath', '/zktest']
}

// WARNING: Do NOT move this task before the "dependencies" declaration; otherwise,
// `configurations.implementation.dependencies` will not work.
task devMode {
	if (project.gradle.startParameter.taskNames.stream().filter {
			it.endsWith('Dev')
		}.findFirst().isPresent()) {
//		dependsOn browsersync
		gretty {
			httpPort = gretty.httpPort
			beforeClassPath = []
			def allowedWorkspace = []
			configurations.implementation.dependencies.each {
				allowedWorkspace << it.group + ":" + it.name
			}
			def subprojectsWithJS = []
			addClassPath(gradle, beforeClassPath, [], allowedWorkspace, subprojectsWithJS)

			println "Watching the following subprojects with browsersync:"
			println subprojectsWithJS
			browsersync.args << '--subprojectPaths' << subprojectsWithJS.join(',')
		}
	}
}

task appRunDev {
	dependsOn devMode
}
task appRunDebugDev {
	dependsOn devMode
}

def addClassPath(gradle, beforeClassPath, visitedBuilds, allowedWorkspace, subprojectsWithJS) {
	gradle.includedBuilds.each {
		if (visitedBuilds.contains(it.name)) return
		visitedBuilds << it.name
		def rootGradle = it.properties['target'].properties['buildController'].gradle
		it.properties['target'].properties['availableModules'].each {

			def prj = rootGradle.rootProject.findProject(it.right.identityPath.toString())
			if (!prj) {
				prj = rootGradle.rootProject.findProject(it.right.projectPath.toString())
			}
			if (prj && allowedWorkspace.contains(prj.group + ":" + prj.name)) {
				beforeClassPath << prj.sourceSets.main.output.resourcesDir
				println "add to classPath: " + prj.sourceSets.main.output.resourcesDir
				subprojectsWithJS << prj.projectDir
			}
		}
		addClassPath(rootGradle, beforeClassPath, visitedBuilds, allowedWorkspace, subprojectsWithJS);
	}
}

appRunDev.dependsOn 'appRun'
appRunDebugDev.dependsOn 'appRunDebug'

task testZATSOnly(type: Test) {
    forkEvery = 1
    maxParallelForks = Runtime.runtime.availableProcessors().intdiv(4) ?: 1
    if (project.hasProperty('maxParallelForks'))
        maxParallelForks = project.maxParallelForks as int

    include "org/zkoss/zktest/zats/bind/advance/BindingParamTest.class"
    include "org/zkoss/zktest/zats/bind/advance/CommunicationTest.class"
    include "org/zkoss/zktest/zats/bind/advance/ComponentParamTest.class"
    include "org/zkoss/zktest/zats/bind/advance/DefaultParamTest.class"
    include "org/zkoss/zktest/zats/bind/advance/EventParamTest.class"
    include "org/zkoss/zktest/zats/bind/advance/ForEachVersusChildrenBindingTest.class"
    include "org/zkoss/zktest/zats/bind/advance/GlobalCommandParamsTest.class"
    include "org/zkoss/zktest/zats/bind/advance/HugeDataTest.class"
    include "org/zkoss/zktest/zats/bind/advance/IfVersusVisibleTest.class"
    include "org/zkoss/zktest/zats/bind/advance/NavigationModelTest.class"
    include "org/zkoss/zktest/zats/bind/advance/PassArgumentsOuterTest.class"
    include "org/zkoss/zktest/zats/bind/advance/PerformanceTest.class"
    include "org/zkoss/zktest/zats/bind/advance/WireComponentsTest.class"
    include "org/zkoss/zktest/zats/bind/advance/WireEventListenersTest.class"
    include "org/zkoss/zktest/zats/bind/advance/WireFromImplicitObjectTest.class"
    include "org/zkoss/zktest/zats/bind/advance/WireFromVariableResolverTest.class"
    include "org/zkoss/zktest/zats/bind/advance/WiringSequenceTest.class"
    include "org/zkoss/zktest/zats/bind/advance/ZKContextObjectParamTest.class"
    include "org/zkoss/zktest/zats/bind/basic/MVP2MVVMTest.class"
    include "org/zkoss/zktest/zats/bind/basic/ModulizeTest.class"
    include "org/zkoss/zktest/zats/bind/basic/PerformanceTest.class"
    include "org/zkoss/zktest/zats/bind/basic/Reattachment_compTest.class"
    include "org/zkoss/zktest/zats/bind/basic/Reattachment_includeTest.class"
    include "org/zkoss/zktest/zats/bind/collection/C1Test.class"
    include "org/zkoss/zktest/zats/bind/collection/C2Test.class"
    include "org/zkoss/zktest/zats/bind/comp/ComboboxTest.class"
    include "org/zkoss/zktest/zats/bind/comp/Combobox_selectedTest.class"
    include "org/zkoss/zktest/zats/bind/comp/CombobuttonTest.class"
    include "org/zkoss/zktest/zats/bind/comp/DatetimeboxTest.class"
    include "org/zkoss/zktest/zats/bind/comp/GridTest.class"
    include "org/zkoss/zktest/zats/bind/comp/GroupboxTest.class"
    include "org/zkoss/zktest/zats/bind/comp/ListboxTest.class"
    include "org/zkoss/zktest/zats/bind/comp/MenuitemTest.class"
    include "org/zkoss/zktest/zats/bind/comp/Radiogroup_selectedTest.class"
    include "org/zkoss/zktest/zats/bind/comp/Tabbox_dynamic_selectionTest.class"
    include "org/zkoss/zktest/zats/bind/comp/Tabbox_selectedTest.class"
    include "org/zkoss/zktest/zats/bind/comp/TreeTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/bindcomposer/BindComposerTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/binder/BinderGlobalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/binder/BinderNotifyQueueTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/commandbinding/CommandTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/converter/ChildrenBindingConverterTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/converter/ConverterTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/el/EL3Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/el/MethodsTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/el/RuntimeEvalTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/F1Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/F2Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/FormProxyDirtyTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/FormWithListTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/FormWithMapTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/form/FormWithSetTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/globalcommand/GlobalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/initialization/InitErrorVMNameTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/initialization/InitTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/propertybinding/BasicPropertyBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/propertybinding/CollectionPropertyBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/propertybinding/ConditionalPropertyBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/propertybinding/TemplatePropertyBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/referencebinding/BasicReferenceBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/referencebinding/ModularizedReferenceBindingTest.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va01Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va02Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va03Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va04Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va05Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va06Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va07Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va08Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va09Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va10Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va11Test.class"
    include "org/zkoss/zktest/zats/bind/databinding/validator/Va12Test.class"
    include "org/zkoss/zktest/zats/bind/el/F80_ZK_2596Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B0004Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B0020Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00603Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00604Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00605Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00611Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00619Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00632Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00634Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00651Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00657Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00678Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00682Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00714Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00722Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00757OnChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00758IndirectTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00762Combobox1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00762Combobox2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00762Listbox1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00762Listbox2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00775ListmodelSelectionTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00807GroupModelListboxMultipleTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00807GroupModelListboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00807GroupModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00810ListboxMultipleTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00821SelectedIndexTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00828GlobalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00847FormInitTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00848ValidationMessagesEmptyTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00849ConverterParametersTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00869SerializationTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00877NPEInSaveOnlyBindingTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00878WrongValueException2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B00878WrongValueExceptionTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00892ChildBindingUnderListboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00905FormNotifyChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00911FormNotifyChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00913ValueReloadTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00950ReferenceChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00967GroupModelListboxMultipleTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00967GroupModelListboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00967GroupModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00992SubModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00993IncludeReloadTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B00994InitParamTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01005BeanValidatorPathTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01016NestedFormTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01017NestedFormPathTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01059DifferentTypeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01060DirectModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01062NullIntValueTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01063BindExceptionTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01066IncorrectFormValueTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01085NPEReferenceBindingTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01088FormUpdateTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01139LoadInitTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01157CorrectConverterNameTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01164ImageContentTypeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01165NestedBinderTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01167ConverterIdxOutOfBoundTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01185CollectionBindingNPETest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01188MixingELWithRefAllTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01188MixingELWithRefTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01189FormNotifyChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01194NestedVMInitTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01196BinderUiLcConfusionTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01259HaskMapInFx1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01259HaskMapInFx2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01268UnsupportChildExpTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01299RefNPETest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01344DeletingEntryTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01347CheckboxCrashTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01366RadioSelectedItemTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01464IncludeReloadTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01468RefIncludeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01469ScopeParamRefTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01472BindIncludeArgTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01528NPEInPagingMold2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01528NPEInPagingMoldTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01529SelectedItemsIndexTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01547NPEWhenCreateNonPageTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01595SelectedItemsTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01615ChildrenBindingInFormTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01640CommandSend2WrongViewModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01666ToolbarbuttonCheckTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01691DropuploadNativeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01699IncludeMultipleTimesTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeChildrenTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeComboboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeGridTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeListboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeRadiogroupTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01787NotifyChangeTreeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01791GlobalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01795NestedTemplateTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01848FormBindingUpdateTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01873SelectedItemOnClickTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01887DetachAttachTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01891ComboboxValidatorTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01895PagingOnListbox2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01895PagingOnListbox3Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01895PagingOnListboxTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01899ComboboxReloadSelectedItemTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01908DatabindingOnPagingTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01938GridListboxActivePageTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B01960BindArray2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B01960BindArrayTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B02022ComponentRemovalTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B02078Test.class"
    include "org/zkoss/zktest/zats/bind/issue/B02083FormRefTest.class"
    include "org/zkoss/zktest/zats/bind/issue/B02592Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F0002Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F0010Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F0011Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F0013Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F0015Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00633Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00638Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00687Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00743_1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00743_2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00769Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00771_1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00771_2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00772InterCommTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00823RadiogroupModel1Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00823RadiogroupModel2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F00843SelectboxSelectedItemTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00862BeanValidator4FormTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00864ValidationContextEasierTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00889ChildrenBindingConverterTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00901ReferenceBindingTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00916FormBeanValidatorTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00921SystemConverterValidatorTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00986CloseWindowTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F00995ValidationMessagesTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01026BindCustomAttrTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01032BindContextEventTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01033InitClassTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01044DeferOnChangeTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01046PublicEventTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01048FormBindingMessageTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01231AfterComposeVMTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01416DefaultCommandTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F01845TabboxModel2Test.class"
    include "org/zkoss/zktest/zats/bind/issue/F01845TabboxModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F02545ChildrenBindingMapTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F02545ChildrenBindingSupportListModelTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F02545ChildrenBindingSupportListModel_AttachDetachTest.class"
    include "org/zkoss/zktest/zats/bind/issue/F02581Test.class"
    include "org/zkoss/zktest/zats/bind/parser/F80_Parser_MVVMAutoApplyTest.class"
    include "org/zkoss/zktest/zats/bind/parser/F80_Parser_StoreSubAnnotCntTest.class"
    include "org/zkoss/zktest/zats/bind/shadow/FlowCtrlNestedTest.class"
    include "org/zkoss/zktest/zats/bind/shadow/FlowCtrlTest.class"
    include "org/zkoss/zktest/zats/bind/shadow/ForEachStatusTest.class"
    include "org/zkoss/zktest/zats/bind/shadow/ForeachTest.class"
    include "org/zkoss/zktest/zats/bind/shadow/TemplateTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/command/GlobalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/command/LocalCommandTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/data/BasicTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/data/CollectionsTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/init/DestroyTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/init/InitTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/init/InitWithParamTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/BasicTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/DependsOnTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/NotifyChangeAutoTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/NotifyChangeDisabledTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/NotifyChangeDynamicTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/NotifyChangeOnSetterTest.class"
    include "org/zkoss/zktest/zats/bind/viewmodel/notification/NotifyChangeTest.class"
    include "org/zkoss/zktest/zats/test2/B100_ZK_4355Test.class"
    include "org/zkoss/zktest/zats/test2/B101_ZK_5677Test.class"
    include "org/zkoss/zktest/zats/test2/B101_ZK_5707Test.class"
    include "org/zkoss/zktest/zats/test2/B101_ZK_5764Test.class"
    include "org/zkoss/zktest/zats/test2/B102_ZK_5758Test.class"
    include "org/zkoss/zktest/zats/test2/B102_ZK_5880Test.class"
    include "org/zkoss/zktest/zats/test2/B102_ZK_5889Test.class"
    include "org/zkoss/zktest/zats/test2/B102_ZK_5904Test.class"
    include "org/zkoss/zktest/zats/test2/B103_ZK_5571Test.class"
    include "org/zkoss/zktest/zats/test2/B103_ZK_5571_1Test.class"
    include "org/zkoss/zktest/zats/test2/B50_2929887Test.class"
    include "org/zkoss/zktest/zats/test2/B50_2946917Test.class"
    include "org/zkoss/zktest/zats/test2/B50_ZK_812Test.class"
    include "org/zkoss/zktest/zats/test2/B65_ZK_1944Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2321Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2539Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2547Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2555Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2562Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2567Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2595_1Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2606Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2611Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2815Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2854Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2857Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2879Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_2958Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_3012Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_3021Test.class"
    include "org/zkoss/zktest/zats/test2/B70_ZK_3045Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_1696_gridTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_1696_listTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_1696_treeTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_1696_tree_2Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_1987_1Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2542Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2715Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2758Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2760Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2763Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2787Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2789Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2792Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2799Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2807Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2808Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2809Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2823Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2833Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2868Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2868_1Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2869Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2908Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2915Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2917Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2921Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2923Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2925Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2927Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2927_2Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2930Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2943Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_2982Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3009Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3022Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3026Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3044Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3066Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3084Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3104_1Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3107Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3110Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3113Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3136Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3149Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_gridTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_grid_norodTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_listTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_list_norodTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_treeTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3173_tree_norodTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3182Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3201Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3208_gridTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3208_listTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3208_treeTest.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3211Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3219Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3251Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3258Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3265Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3282Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3283Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3312Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3517Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3546Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3562Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3576Test.class"
    include "org/zkoss/zktest/zats/test2/B80_ZK_3611Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3570Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3585Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3630Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3642Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3653Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3698Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3713Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3738Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3749Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3765Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3771Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3811Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3812Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3814Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3815Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3828Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3867Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3871Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3881Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3935Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3944Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3969Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3972Test.class"
    include "org/zkoss/zktest/zats/test2/B85_ZK_3988Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4026Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4029Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4053Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4099Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4128Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4146Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4190_2Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4195Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4220Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4221Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4236Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4271Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4280Test.class"
    include "org/zkoss/zktest/zats/test2/B86_ZK_4366Test.class"
    include "org/zkoss/zktest/zats/test2/B90_ZK_4447Test.class"
    include "org/zkoss/zktest/zats/test2/B90_ZK_4526Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4281Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4410Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4515Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4549Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4613Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4685Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4686Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4686_1Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4688Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4698Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4722Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4749Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4756Test.class"
    include "org/zkoss/zktest/zats/test2/B95_ZK_4776Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_2297Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_3543Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_3563Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4763Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4778Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4791Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4800Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4832Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4845Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4855Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4877Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4889Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4892Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4893Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4896Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4897Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4903Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_4945Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5002Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5043Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5079Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5179Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5208Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5223Test.class"
    include "org/zkoss/zktest/zats/test2/B96_ZK_5382Test.class"
    include "org/zkoss/zktest/zats/test2/F100_ZK_5018Test.class"
    include "org/zkoss/zktest/zats/test2/F100_ZK_5024Test.class"
    include "org/zkoss/zktest/zats/test2/F100_ZK_5408Test.class"
    include "org/zkoss/zktest/zats/test2/F100_ZK_5408_1Test.class"
    include "org/zkoss/zktest/zats/test2/F50_2816083Test.class"
    include "org/zkoss/zktest/zats/test2/F60_ZK_1047Test.class"
    include "org/zkoss/zktest/zats/test2/F70_ZK_2002Test.class"
    include "org/zkoss/zktest/zats/test2/F70_ZK_2483Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2476Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2508Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2612Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2642Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2642_2Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2662Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2718Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2800Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2944Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2944_1Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2944_2Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2951Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_2955Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_3144Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_3157Test.class"
    include "org/zkoss/zktest/zats/test2/F80_ZK_3351Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_1148Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_2459Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3324Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3329_2Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3684Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3711_1Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3762Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3797Test.class"
    include "org/zkoss/zktest/zats/test2/F85_ZK_3816Test.class"
    include "org/zkoss/zktest/zats/test2/F86_ZK_4028Test.class"
    include "org/zkoss/zktest/zats/test2/F86_ZK_4028_mvcTest.class"
    include "org/zkoss/zktest/zats/test2/F86_ZK_4203Test.class"
    include "org/zkoss/zktest/zats/test2/F90_ZK_4347_errorsTest.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4508Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4523Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4552Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4569Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4582Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4649_init2Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4649_initTest.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4649_setter2Test.class"
    include "org/zkoss/zktest/zats/test2/F95_ZK_4649_setterTest.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4330_3Test.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4751Test.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4751_legacyTest.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4810Test.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4810_2Test.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4934_ListModelArrayTest.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4934_ListModelListTest.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4934_ListModelMapTest.class"
    include "org/zkoss/zktest/zats/test2/F96_ZK_4934_ListModelSetTest.class"

    useJUnitPlatform()

    systemProperty "zkWebdriverContextPath", "/zktest"
    systemProperty "zkWebdriverTestURLPackage", "org.zkoss.zktest.zats"

    options {
        systemProperties(System.getProperties())
    }

    testLogging {
        events("standardOut", "started", "passed", "skipped", "failed")
    }

    maxHeapSize = "1024m"
    jvmArgs '-XX:MaxMetaspaceSize=1024m'
}
