name: Check-PR-Files
on:
  pull_request_target:
    types: [opened]

jobs:
  check-pr-files:
    runs-on: ubuntu-latest
    steps:
      - uses: zkoss/check-pr-files-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}