name: WIP
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  repository_dispatch:
    types: [rebase-command]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: zkoss/wip-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}